### ISSUE TITLE
missing login and capability checks.

### ISSUE THREAD

**Issue by danmarsden** [dualcube/moodle-gradereport_quizanalytics#1]
Hi there, 

I'm reviewing this plugin for approval in the moodle.org plugins db.

looks like many of the pages in this plugin are available to anonymous users - you should be adding require_course_login/require_login and capability checking.

I'd advise you take a look at the other general security guidelines too:
https://docs.moodle.org/dev/Security#Summary_of_the_guidelines

**Comment by kndnsow** [comment]
it's solved and added in the latest version
