### ISSUE TITLE
Can this be translated?

### ISSUE THREAD

**Issue by dinism** [dualcube/moodle-gradereport_quizanalytics#10]
**THANKS**
![imagem](https://user-images.githubusercontent.com/14828021/87077784-905ad980-c21b-11ea-8a0a-1c862ea74cea.png)
![imagem](https://user-images.githubusercontent.com/14828021/87077815-9c469b80-c21b-11ea-9fd2-ae572eeb8969.png)
![imagem](https://user-images.githubusercontent.com/14828021/87077837-a4064000-c21b-11ea-9ad0-a25d4ae8ac5c.png)
![imagem](https://user-images.githubusercontent.com/14828021/87077866-ab2d4e00-c21b-11ea-86f6-07805a5418fd.png)
![imagem](https://user-images.githubusercontent.com/14828021/87077892-b7191000-c21b-11ea-9f99-1d9a46cc2304.png)

**Comment by kndnsow** [comment]
it's solved and added in the latest version
