### ISSUE TITLE
dml readexceptions on fetchdata.php (clicking view analytics link)

### ISSUE THREAD

**Issue by jfssystems** [dualcube/moodle-gradereport_quizanalytics#11]
Hi,

Testing the plugin on moodle 3.6.4 gives some Database / SQL exceptions (clicking view analytics link). Any ideas ?

ERROR: column "mdl_quiz_attempts.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT * FROM mdl_quiz_attempts
^
SELECT * FROM mdl_quiz_attempts
WHERE state = 'finished' AND sumgrades IS NOT NULL AND quiz = $1
AND sumgrades >= $2 GROUP BY userid
[array (
0 => 1168,
1 => 8.4000000000000004,
)]
Error code: dmlreadexception
* line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
* line 859 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()

and 

 ERROR: invalid input syntax for type numeric: "NULL"
LINE 5: AND quizatt.sumgrades <> 'NULL' AND quizatt....

**Comment by kndnsow** [comment]
it's solved and added in the latest version
