### ISSUE TITLE
Quiz analytics is not respecting quiz and gradebook visibility settings

### ISSUE THREAD

**Issue by guyheli** [dualcube/moodle-gradereport_quizanalytics#12]
Students can view analytics for hidden quizzes.

Moodle 3.5, quiz_analytics 1.1 (Build: 2017081602)

**Comment by moodleulpgc** [comment]
This is still true for last version of the plugin. 
teacher at my University complain that students can see single question report (if wrong or right) even during quiz attempt, and ignoring quiz feedback settings. That is, even if quiz instance settings are set to prevent students to see if an answer  is right or not, or the final grade, they can see it through this plugin. The teachers  see that as a security hole. 

Having a look into code, I see that the plugin  gets all raw instances form database (index.php line 128 
$getquizrecords = $DB->get_records('quiz', array('course' => $courseid));
And there is no provision to get coursemodule visibility or to load attempt review/feedback options.  
In my opinion, not honoring the instance access/review settings IS a problem, a bug that must be solved.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
