### ISSUE TITLE
please use DML parameters instead of adding vars into inline sql

### ISSUE THREAD

**Issue by danmarsden** [dualcube/moodle-gradereport_quizanalytics#2]
for example:
https://github.com/dualcube/moodle-gradereport_quizanalytics/blob/master/fetchdata.php#L43

$quizid should not be added directly to the sql string - you should be passing this as a param like shown in the docs here:
https://docs.moodle.org/dev/Data_manipulation_API#moodle_database::get_records_sql.28.29

there are many other examples in your code that do this and should be fixed prior to approval in the plugins db.

**Comment by parthajeet** [comment]
Thanks for pointing these out, we have uploaded another version with these fixed. Please check and let us know.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
