### ISSUE TITLE
Language Customization Failure

### ISSUE THREAD

**Issue by interactivelessons** [dualcube/moodle-gradereport_quizanalytics#21]
Hi, When I install this plugin, I cannot access to Language Customization page. I tried by unstalling this plugin, everything worked fine.

![failure](https://user-images.githubusercontent.com/25821804/206123786-34f2103c-1623-4970-98a8-4251d81da644.png)

**Comment by senaiboy** [comment]
Having the exact same issue here.

**Comment by jhutch1** [comment]
I was able to fix this by editing line 98 of lang/en/gradereport_quizanalytics.php.

Original line is:

_$string['cutOffscore'] = 'Cut Off Score';_

Edited line is:

_$string['cutoffscore'] = 'Cut Off Score';_

I don't think Moodle likes capital letters in its language string names.

**Comment by kndnsow** [comment]
it's solved and added in the latest version

**Comment by zishanj** [comment]
This issue is still in the latest release.
