### ISSUE TITLE
Quiz Analytics is not showing Quiz Question Category, instead its picking from other Courses.

### ISSUE THREAD

**Issue by ashishsriphd** [dualcube/moodle-gradereport_quizanalytics#22]
Quiz Analytics is not showing Quiz Question Category, instead it's picking Question Categories from other Courses.

[Moodle Quiz Question Bank Category- Quiz Analytics.pdf](https://github.com/dualcube/moodle-gradereport_quizanalytics/files/11612101/Moodle.Quiz.Question.Bank.Category-.Quiz.Analytics.pdf)

**Comment by kndnsow** [comment]
solved on latest version
