### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by moumitahalder** [dualcube/moodle-gradereport_quizanalytics#26]
I list Quiz Analytics in a course grades, while there are many graded attempts, it shows as there are no attempts and under action there is no link (Not yet graded). I am using Moodle 3.11 and another instance on Moodle 4.1 with the same issues.

Any suggestions?

On the other hand as suggestions, it lists only 5 quizzes, they need to be controlled and able to make it list more, possibly by defining the number of quizzes to show at a time.

Also as a suggestion, it needs to have filtration, in one course, I have over 50 quizzes and looking for a specific quiz will be a long process, so it is important to have the filters.

**Comment by kndnsow** [comment]
solved on latest version
