### ISSUE TITLE
Add release version tags in this repo.

### ISSUE THREAD

**Issue by chyrka** [dualcube/moodle-gradereport_quizanalytics#32]
Thank you for developing additional features for Moodle. 
You push all updates (releases) in the master branch without creating other branches or tags. 
Could you please add tags for releases on Git repository as it is very difficult to keep track of updates to this plugin?

Thanks

**Comment by kndnsow** [comment]
Thank you for your feedback. 
 We'll do our best to make it happen.
We are actively maintaining release information by responding to and closing issues. 
You can find additional details in our closed issues section.
