### ISSUE TITLE
Unable to view analytics

### ISSUE THREAD

**Issue by nina29** [dualcube/moodle-gradereport_quizanalytics#4]
I am unable to retrieve the information when I click on the View Analytics link. No action is happening,

**Comment by parthajeet** [comment]
Dear Nina,

Are you seeing any error during the process? Can you send a screenshot so that we can check the issue ?

Thank you.

**Comment by nina29** [comment]
Hello,

I don't get any errors, just click on the View Analytics link, and nothing happens. I am using Moodle 3.5, but no errors were shown when I installed the plugin. 

Thank you.
![quiz analytics](https://user-images.githubusercontent.com/14388486/47513803-427e2200-d83c-11e8-9b97-759c6f40976b.png)

**Comment by parthajeet** [comment]
Dear Nina,
We could not reproduce the error. Please share your admin credentials and FTP so that we can fix this on your site.

You can email to: suman.d@dualcube.com

Thank you.

**Comment by chemacortes** [comment]
I got the same error. With Firefox, javascript stops with an exception "ReferenceError: Emtpy is not defined" at function __wrapper into sdk:js:109. With chrome, it works fine.

I'm using moodle 3.6.2 and firefox 65.0.1

**Comment by parthajeet** [comment]
We have checked it in Moodle 3.6.2 and Firefox 65.0.1. It works perfectly.
Please check the image: 
![firefox](https://user-images.githubusercontent.com/8317605/52936385-f6726280-3381-11e9-9078-2841e2db0aab.png)
Thank you.

**Comment by chemacortes** [comment]
OK. I can add more info. At the call to graph api at the begin of index.php, become this:

```
<script type="text/javascript">
    window.fbAsyncInit = function() {
        FB.init({
            appId      : Empty,
            xfbml      : true,
            version    : "Empty"
        });
    };
```
`Empty` is not defined. Firefox stops the execution; Chrome continues.

The original php code is:

```
<script type="text/javascript">
    window.fbAsyncInit = function() {
        FB.init({
            appId      : <?php echo $CFG->gradereport_quizanalytics_fbappid; ?>,
            xfbml      : true,
            version    : "<?php echo $CFG->gradereport_quizanalytics_apiversion; ?>"
        });
    };
```
I has not configured the FB ID in my moodle. This is the problem, isn't it?

**Comment by parthajeet** [comment]
Hello, 

It shouldn't be. Can you add FB ID and then check whether it is working or not?

**Comment by chemacortes** [comment]
Sorry for the delay. I try with a FB ID and API version. The error has gone, but the extension does nothing with firefox. But it works now if I start firefox on safe mode. Sure, I has a an extension in conflict with analytics.

**Comment by parthajeet** [comment]
Please disable the extensions and then use the plugin. We have tested it on fresh Firefox.
Thank you.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
