### ISSUE TITLE
Error while loading the javascript 

### ISSUE THREAD

**Issue by bhos-ly** [dualcube/moodle-gradereport_quizanalytics#5]
Hi, we have installed the plugin in moodle v3.6.7, and when we try it there is an error when loading the javascript. See the console error hereafter.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/6949998/69437797-3bc62500-0d44-11ea-8fb2-7257e063f0ca.png)

**Comment by trideepdm** [comment]
Please update your plugin. Thank you.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
