### ISSUE TITLE
Link Report URL after Quiz Attempt

### ISSUE THREAD

**Issue by SanatSharma** [dualcube/moodle-gradereport_quizanalytics#6]
Hi,
I love this plugin, thanks a lot. When a user attempts a quiz, they have the option to review their performance. I would like to include a link to the report for that quiz here in the Quiz mod itself, rather than having to go to Grades.
How would this be possible?

**Comment by sumandualcube** [comment]
Dear @SanatSharma For this feature, you will need to customise the plugin. Since, this is not a requirement of majority of our users, this won't be added with an update. If you can customise it, it would be great. Otherwise, please send a custom request email to admin@dualcube.com.

Thank you.

**Comment by SanatSharma** [comment]
Hi I understand. I was asking if you could give a hint of what changes
would be needed. I can do them.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
