### ISSUE TITLE
"View Analytics" gives a POST fetchdata 404 not found

### ISSUE THREAD

**Issue by hmgp** [dualcube/moodle-gradereport_quizanalytics#7]
Hello, I'm trying to get the plugin to work. It has not been easy... I've Moodle 3.7. Plugin installed without errors. Initially it did not work when click on "View Analytics". 
First, I discovered it's mandatory to have an Facebook API key. Done that. 
Them it gave me a "invalid version specified" which I had to change the index.php to have js.src = "//connect.facebook.net/en_US/all.js"; where it was js.src = "//connect.facebook.net/en_US/sdk.js";
Now, when I click "View Analytics" it gives me "jquery-3.2.1.min.js:1 POST https://www.xxx.yy/grade/report/quizanalytics/fetchdata.php 404 (Not Found)".
And I can't get out of this one by myself. Can you help? Thank you!

**Comment by hmgp** [comment]
Just to add to the explanation, an image of the error:
![Screenshot from 2020-05-28 12-49-51](https://user-images.githubusercontent.com/52750094/83137940-ec412700-a0e1-11ea-9034-b881b5cb0644.png)

I checked and every file in that message exists and is accessible.
Any clues?
Thank you.

**Comment by hmgp** [comment]
Can anyone give some help? Some clue to the problem? Thank you.

**Comment by trideepdm** [comment]
Please update your plugin. Thank you.

**Comment by hmgp** [comment]
Hi, thank you very much. I updated the plugin as requested. But I still get error and no results.

So, standard install gives me this error:

![Screenshot from 2020-06-05 10-05-48](https://user-images.githubusercontent.com/52750094/83858630-b10fab00-a714-11ea-92c4-be7f377559d1.png)

If I change line 52 of file grade/report/quizanalytics/index.php, I pass the SDK.JS error but still get this:

![Screenshot from 2020-06-05 10-07-38](https://user-images.githubusercontent.com/52750094/83858739-d8667800-a714-11ea-9243-fa10e9cb0922.png)


If I can help debug, please just say what you want me to do.

One other question, does this work with aggregated results? I mean, can a teacher see the report for all the user of the quiz? Or is just a report for the single student?

Again thank you very much.

**Comment by trideepdm** [comment]
Dear hmgp,
I tested this plugin before the update and it's working fine. So in your case, it may be folder/file permission issue. Please give 644 as file permission to that particular file (fetchdata.php) and other files also and set the folder permission as 755.
Thank you.

**Comment by hmgp** [comment]
Hello! Tank you for your help.
No, it's not a permission problem:
![Screenshot from 2020-06-05 16-32-10](https://user-images.githubusercontent.com/52750094/83895186-44af9e80-a74a-11ea-8f08-e89f9b770d68.png)

and the error it's there:
![Screenshot from 2020-06-05 16-31-39](https://user-images.githubusercontent.com/52750094/83895249-55f8ab00-a74a-11ea-989f-10a2f1361dc2.png)

Can I help by making some debug? Try to get more info?

**Comment by trideepdm** [comment]
Yes, you can. 
As we are not getting this issue on our testing instances so you can share your stagging site's FTP and admin user access to this mail address trideepdm@dualcube.com then I can test this issue on your site.
Thank you.

**Comment by hmgp** [comment]
Sorry, it's am institutional website, even being a test one, and I cannot share access. I'm not allowed.
But I'm am a computer person and I can make what you ask and send reports.

**Comment by hmgp** [comment]
Hello. I can help. Tell me what you need to debug this. 

Thank you.

**Comment by hmgp** [comment]
Hello, just remembering I can help with debug, just tell me what you would like to see.
Thank you.

**Comment by kndnsow** [comment]
it's solved and added in the latest version
