### ISSUE TITLE
Quiz analytic option shows Number of Attempts 0 when I have an answered quiz.  

### ISSUE THREAD

**Issue by monicobr** [dualcube/moodle-gradereport_quizanalytics#8]
Hey guys excellent job with this fantastic quiz report plugin. I decided to test it. I create a demo quiz with three questions. I created demo user to take this demo quiz. The quiz was graded after the demo user took the demo quiz However, in the Quiz Analytics option shows the following information

Quiz Name Number of Attempts Action
Demostration Quiz 0 Not yet Graded

This Quiz Analytic information is the opposite that I have in the grade section of this Quiz.

Any idea how I can fix this quiz report issue?

Thanks in advance

**Comment by sumandualcube** [comment]
@monicobr 

Thanks for appreciating our effort. Can you please tell us your Moodle version and the plugin version and build number that you are using?

Thank you.

**Comment by monicobr** [comment]
Hey there. I appreciate your time to reply my message. I decided to create a PDF file to copy and paste all information you require to me. Also, I include two images where you can verify the quizanalytic scenario that I have. Thanks in Advance
[quizanalyticfeatures.pdf](https://github.com/dualcube/moodle-gradereport_quizanalytics/files/4907172/quizanalyticfeatures.pdf)

**Comment by acquaalta** [comment]
Hi @sumandualcube 
I'm using Moodle 3.10 and experiencing the same issue - There is a finished attempt in the quiz,  but the "Quiz Analytics" tab says "Number of Attempts" is 0 and "Action" is "Not yet Graded".

Could you please clarify this issue?
