### ISSUE TITLE
Word hardcoded

### ISSUE THREAD

**Issue by dinism** [dualcube/moodle-gradereport_quizanalytics#9]
Thanks for the plugin.
I'm a PT-PT translator.
![imagem](https://user-images.githubusercontent.com/14828021/87074862-67384a00-c217-11ea-97db-dfb6116c7b85.png)
![imagem](https://user-images.githubusercontent.com/14828021/87074883-70291b80-c217-11ea-95b1-66ad09efb959.png)
![imagem](https://user-images.githubusercontent.com/14828021/87074937-82a35500-c217-11ea-9d1a-2439d9dbf2f2.png)
**In file index.php**
![imagem](https://user-images.githubusercontent.com/14828021/87075053-aebed600-c217-11ea-8c73-d5b3c1d96760.png)

**Comment by kndnsow** [comment]
it's solved and added in the latest version
